version: '3.9'
#here we define the differents services that make up our compose
services:
  #wordpress service definition for FARGATE in ecs cluster
  wordpress:
   image: wordpress:latest
   ports:
     - '80:80'
   restart: always
   volumes:
     - ./wordpress:/var/wwww/html
   environment:
     WORDPRESS_DB_HOST: <rds_endpoint>:3306
     WORDPRESS_DB_USER: oriuser2023
     WORDPRESS_DB_PASSWORD: Mpandzou1989
     WORDPRESS_DB_NAME: oridb2023
     #WORDPRESS_DB_WAIT_TIME: 1
     WORDPRESS_ADMIN_EMAIL: gaelducongo@yahoo.com
     WORDPRESS_ADMIN_PASSWORD: Mp$ndzou1989
     WORDPRESS_ADMIN_USER: wpuser2023
     WORDPRESS_SITE_TITLE: ORI DEVOPS TEAM - CARD 220064